name: Update events

on:
  watch:
    types: started
  schedule:
    - cron:  '35 5 * * 1'

jobs:
  update-social:
    runs-on: ubuntu-latest
    steps:
      - name: Social Readme
        uses: zylele/social-readme@master
        with:
          blog_rss_link: 需要修改/atom.xml
          blog_limit: 10
          douban_name: 需要修改
          douban_limit: 10
